-- =========================================================
-- TRUCOST Supabase schema
-- Paste this whole file into Supabase → SQL Editor → Run.
-- Safe to run again: it never deletes TRUCOST data.
--
-- The app reads and writes these tables from the server with the
-- service role key. Row Level Security is on with no policies, so the
-- public anon key can't read or change anything (password hashes,
-- sessions and messages stay private).
-- =========================================================

create extension if not exists citext with schema extensions;

-- ---------------------------------------------------------
-- Remove the earlier Logbook test tables (profiles/vehicles design).
-- They were empty. Only runs while they still have the old shape.
-- ---------------------------------------------------------
do $$
begin
  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'listings' and column_name = 'vehicle_id') then
    drop table public.listings cascade;
  end if;
  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'messages' and column_name = 'receiver_id') then
    drop table public.messages cascade;
  end if;
end $$;
drop table if exists public.listing_images, public.vehicles, public.profiles cascade;
drop function if exists public.update_updated_at_column() cascade;

-- ---------------------------------------------------------
-- Accounts
-- ---------------------------------------------------------
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email extensions.citext not null unique,
  name text not null,
  phone text not null default '',
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  -- Quote details from sign-up (licence, claims, cover...), see lib/driver-profile.ts.
  details jsonb not null,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

-- The cookie holds a random token; only its SHA-256 hash is stored.
create table if not exists public.sessions (
  token_hash text primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists sessions_user on public.sessions(user_id);

-- ---------------------------------------------------------
-- Listings. seller_id is null for the demo listings.
-- Deleting a user deletes their listings.
-- ---------------------------------------------------------
create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  seller_id uuid references public.users(id) on delete cascade,
  make text not null,
  model text not null,
  year int not null,
  engine_size_litres numeric(3,1) not null,
  price int not null,
  odometer_km int not null,
  location text not null,
  colour text not null default '',
  description text not null default '',
  created_at date not null default current_date
);
create index if not exists listings_seller on public.listings(seller_id);

-- One photo per listing, uploaded by the seller (base64). Deleted with the listing.
create table if not exists public.listing_photos (
  listing_id bigint primary key references public.listings(id) on delete cascade,
  mime text not null,
  data text not null,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------
-- Messages: one conversation per listing and buyer. The read times
-- mark how far each side has read (null = nothing read yet).
-- ---------------------------------------------------------
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  listing_id bigint not null references public.listings(id) on delete cascade,
  buyer_id uuid not null references public.users(id) on delete cascade,
  seller_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  buyer_read_at timestamptz,
  seller_read_at timestamptz,
  unique (listing_id, buyer_id)
);
create index if not exists conversations_buyer on public.conversations(buyer_id, last_message_at);
create index if not exists conversations_seller on public.conversations(seller_id, last_message_at);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);
create index if not exists messages_conversation on public.messages(conversation_id, id);

-- ---------------------------------------------------------
-- Inbox: a user's conversations with unread count, the other
-- person's name and the last message.
-- ---------------------------------------------------------
create or replace function public.conversation_list(p_user uuid)
returns table (
  id uuid,
  listing_id bigint,
  seller_id uuid,
  last_message_at timestamptz,
  unread bigint,
  other_name text,
  last_id bigint,
  last_sender_id uuid,
  last_body text,
  last_created_at timestamptz
)
language sql stable
set search_path = public
as $$
  select
    c.id, c.listing_id, c.seller_id, c.last_message_at,
    (select count(*) from messages m
      where m.conversation_id = c.id and m.sender_id <> p_user
        and m.created_at > coalesce(case when c.buyer_id = p_user then c.buyer_read_at else c.seller_read_at end, '-infinity')),
    u.name,
    lm.id, lm.sender_id, lm.body, lm.created_at
  from conversations c
  left join users u on u.id = case when c.buyer_id = p_user then c.seller_id else c.buyer_id end
  left join lateral (
    select * from messages m where m.conversation_id = c.id order by m.id desc limit 1
  ) lm on true
  where c.buyer_id = p_user or c.seller_id = p_user
  order by c.last_message_at desc;
$$;

-- ---------------------------------------------------------
-- Lock everything down: server (service role) access only.
-- ---------------------------------------------------------
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.listings enable row level security;
alter table public.listing_photos enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
revoke execute on function public.conversation_list(uuid) from public, anon, authenticated;

-- ---------------------------------------------------------
-- Demo listings, added only while there are no listings yet.
-- Their photos are public/cars/<id>.jpg.
-- ---------------------------------------------------------
insert into public.listings (id, make, model, year, engine_size_litres, price, odometer_km, location, colour, description, created_at)
select * from (values
  (1, 'Toyota', 'Yaris', 2019, 1.0, 13950, 68000, 'Dublin', 'Blue', 'One owner, full Toyota service history. Ideal first car, very cheap to run.', date '2026-09-20'),
  (2, 'Volkswagen', 'Golf', 2017, 1.4, 14500, 112000, 'Cork', 'Grey', 'TSI Highline, heated seats, new tyres and NCT until next year.', date '2026-09-18'),
  (3, 'Skoda', 'Octavia', 2018, 1.6, 13750, 131000, 'Galway', 'White', 'Huge boot, reliable family car. Cambelt done at 150k.', date '2026-09-22'),
  (4, 'Ford', 'Fiesta', 2022, 1.0, 17450, 38000, 'Limerick', 'Black', 'ST-Line EcoBoost, Bluetooth, two keys. Small scuff on rear bumper.', date '2026-09-15'),
  (5, 'Hyundai', 'Tucson', 2021, 1.6, 27900, 54000, 'Kildare', 'Red', 'Executive spec with panoramic roof and reversing camera. Balance of warranty.', date '2026-09-24'),
  (6, 'Nissan', 'Qashqai', 2018, 1.2, 16450, 91000, 'Kilkenny', 'White', 'SV model, sat nav, 360 camera. Serviced every year at main dealer.', date '2026-09-19'),
  (7, 'BMW', '3 Series', 2015, 2.0, 13250, 149000, 'Dublin', 'Red', '320i M Sport, leather interior, recently serviced.', date '2026-09-12'),
  (8, 'Mazda', 'MX-5', 2012, 1.8, 8900, 121000, 'Wicklow', 'Red', 'Roadster, new soft top, great summer car.', date '2026-09-10'),
  (9, 'Toyota', 'Corolla', 2023, 1.8, 27950, 29000, 'Waterford', 'Black', 'Luna trim, adaptive cruise, Apple CarPlay. Full history.', date '2026-09-25'),
  (10, 'Audi', 'A6', 2013, 3.0, 11500, 187000, 'Louth', 'Silver', 'Quattro, S line, very well kept. Timing chain replaced.', date '2026-09-08'),
  (11, 'Dacia', 'Sandero', 2023, 1.0, 15750, 21000, 'Mayo', 'Silver', 'Nearly new, Comfort trim, manufacturer warranty remaining.', date '2026-09-26'),
  (12, 'Ford', 'Mustang', 2018, 5.0, 39000, 48000, 'Meath', 'Red', 'GT V8 fastback, imported and registered. A weekend car with running costs to match.', date '2026-09-05')
) as demo(id, make, model, year, engine_size_litres, price, odometer_km, location, colour, description, created_at)
where not exists (select 1 from public.listings);

-- New listings continue after the highest id.
select setval(pg_get_serial_sequence('public.listings', 'id'), greatest((select max(id) from public.listings), 1));

-- =========================================================
-- Make someone an admin by hand (or add their email to ADMIN_EMAILS):
--   update public.users set role = 'admin' where email = 'you@example.com';
-- =========================================================
