import type { Fuel } from "./valuation";

// Common cars on Irish roads. Used for form suggestions and for filling the
// market database in bulk (see app/api/market/refresh).
export const POPULAR_MODELS: { make: string; model: string; fuel: Fuel }[] = [
  { make: "Toyota", model: "Corolla", fuel: "hybrid" },
  { make: "Toyota", model: "Yaris", fuel: "hybrid" },
  { make: "Toyota", model: "C-HR", fuel: "hybrid" },
  { make: "Toyota", model: "RAV4", fuel: "hybrid" },
  { make: "Volkswagen", model: "Golf", fuel: "petrol" },
  { make: "Volkswagen", model: "Golf", fuel: "diesel" },
  { make: "Volkswagen", model: "Polo", fuel: "petrol" },
  { make: "Volkswagen", model: "Tiguan", fuel: "diesel" },
  { make: "Volkswagen", model: "Passat", fuel: "diesel" },
  { make: "Volkswagen", model: "ID.4", fuel: "electric" },
  { make: "Hyundai", model: "Tucson", fuel: "petrol" },
  { make: "Hyundai", model: "Tucson", fuel: "diesel" },
  { make: "Hyundai", model: "i30", fuel: "petrol" },
  { make: "Hyundai", model: "Kona", fuel: "electric" },
  { make: "Skoda", model: "Octavia", fuel: "diesel" },
  { make: "Skoda", model: "Octavia", fuel: "petrol" },
  { make: "Skoda", model: "Fabia", fuel: "petrol" },
  { make: "Skoda", model: "Superb", fuel: "diesel" },
  { make: "Skoda", model: "Karoq", fuel: "diesel" },
  { make: "Ford", model: "Focus", fuel: "petrol" },
  { make: "Ford", model: "Focus", fuel: "diesel" },
  { make: "Ford", model: "Fiesta", fuel: "petrol" },
  { make: "Ford", model: "Kuga", fuel: "diesel" },
  { make: "Nissan", model: "Qashqai", fuel: "petrol" },
  { make: "Nissan", model: "Qashqai", fuel: "diesel" },
  { make: "Nissan", model: "Juke", fuel: "petrol" },
  { make: "Nissan", model: "Leaf", fuel: "electric" },
  { make: "Kia", model: "Sportage", fuel: "diesel" },
  { make: "Kia", model: "Sportage", fuel: "hybrid" },
  { make: "Kia", model: "Ceed", fuel: "petrol" },
  { make: "Kia", model: "Niro", fuel: "hybrid" },
  { make: "Audi", model: "A3", fuel: "diesel" },
  { make: "Audi", model: "A4", fuel: "diesel" },
  { make: "Audi", model: "A6", fuel: "diesel" },
  { make: "BMW", model: "1 Series", fuel: "diesel" },
  { make: "BMW", model: "3 Series", fuel: "diesel" },
  { make: "BMW", model: "5 Series", fuel: "diesel" },
  { make: "Mercedes-Benz", model: "A-Class", fuel: "diesel" },
  { make: "Mercedes-Benz", model: "C-Class", fuel: "diesel" },
  { make: "Mercedes-Benz", model: "E-Class", fuel: "diesel" },
  { make: "Renault", model: "Clio", fuel: "petrol" },
  { make: "Peugeot", model: "208", fuel: "petrol" },
  { make: "Peugeot", model: "2008", fuel: "petrol" },
  { make: "Peugeot", model: "3008", fuel: "diesel" },
  { make: "Opel", model: "Corsa", fuel: "petrol" },
  { make: "Opel", model: "Astra", fuel: "diesel" },
  { make: "Dacia", model: "Duster", fuel: "diesel" },
  { make: "Dacia", model: "Sandero", fuel: "petrol" },
  { make: "Honda", model: "Civic", fuel: "petrol" },
  { make: "Mazda", model: "CX-5", fuel: "diesel" },
  { make: "Tesla", model: "Model 3", fuel: "electric" },
  { make: "Tesla", model: "Model Y", fuel: "electric" },
];

export const POPULAR_MAKES = [...new Set(POPULAR_MODELS.map((m) => m.make))].sort();
export const POPULAR_MODEL_NAMES = [...new Set(POPULAR_MODELS.map((m) => m.model))].sort();
